import avatar from "@assets/images/avatar.svg"
import featureImg from "@assets/images/Admin/opportunity.svg"
import { opportunity } from "@constants/index.types"

export const opportunities: opportunity[] = [
    {
        id: "001",
        tag: "Admission",
        title: "PhD student in Zoological Systematics",
        faetureImg: featureImg,
        content: "If you plan to travel to the United States from Nigeria and it is your first time, make sure you carry along with you the following documents to prevent",
        status: "Approved",
        author: {
            firstName: "John",
            lastName: "Doe",
            profilePic: avatar,
        },
        funded:"Fully Funded",
        createdAt: "2024-06-20T08:45:30",
        desc: " Fully funded four-year PhD studentship available in Stockholm to work on species diversity of Acoelomorpha including fieldwork, microscopy,eDNA and phylogenetics. We invite applications for a four-year PhD position based at the Swedish Museum of Natural History in Stockholm.PhD students at the museum are admitted to the PhD programme at the Department of Zoology, Stockholm University.The project is aimed at analysing species diversity of the marine meiofauna group Acoelomorpha in Sweden, estimate the phylogeny of select groups and describe new species. The project includes fieldwork at marine labs where specimens will be collected, identified, documented, and prepared for downstream analyses. The position is for four years. A new position as a PhD student is first for one year and then normally renewed for up to two years at a time.  The successful candidate will be supervised by Prof. Ulf Jondelius.",
        benefit: " at least 120 higher education credits in biology, and at least 30 credits from a degree project within zoological systematics, marine biology, evolutionary biology, bioinformatics, or a similar subject Experience in the study of microscopic animals, marine biological fieldwork, analysis of nucleotide sequence data, molecular lab techniques and a strong interest in biodiversity are important qualifications.",
        entryRequirements: "In order to meet the general entry requirements, the applicant must have: completed a second-cycle degree, completed courses equivalent to at least 240 higher education credits, of which 60 credits must be in the second cycle, or have otherwise acquired equivalent knowledge in Sweden or elsewhere. at least 120 higher education credits in biology, and at least 30 credits from a degree project within zoological systematics, marine biology, evolutionary biology, bioinformatics, or a similar subject. Experience in the study of microscopic animals, marine biological fieldwork, analysis of nucleotide sequence data, molecular lab techniques and a strong interest in biodiversity are important qualifications.",
        documentRequirements: "Applicants must meet both University and program requirements. Each graduate program sets their own admissions requirements. These requirements may include: a GPA higher than the university standard standardized test scores letters of recommendation statement of purpose You can upload unofficial transcripts with your application. If more academic documents are necessary, you can email them to us.SU will email you with the program's decision. If the program approves your admission, you will need to provide official transcripts. WVU needs to have your official bachelor's degree transcript before we send your University admission letter or your I-20.",
        eligibilityRegion: " Australia, Canada, Republic of Ireland, New Zealand, United Kingdom, United States and its territories, Liberia, Nigeria, Ghana, Nepal, India, Pakistan, Commonwealth Caribbean Countries (Anguilla, Antigua, The Bahamas, Barbados, Belize, British Virgin Islands, Bermuda, Cayman Islands, Dominica, Grenada, Guyana, Jamaica, Montserrat, St Kitts and Nevis, St Lucia, St Vincent, Trinidad and Tobago, Turks and Caicos).",
        howToApply: "Some programs consider applicants who do not meet those requirements for Intensive English Program (IEP) conditional admission. You may ask your program about conditional admission. Conditionally admitted students must enroll in the WVU IEP until they achieve one of the English proficiency scores listed above.",
        deadline:"15th December, 2023.",
    },
    {
        id: "002",
        tag: "Scholarship",
        title: "Documents to carry when traveling",
        faetureImg: featureImg,
        content: "The Zoology department in the University of Ohio is seeking for a qualified candidate for a Research Assistant position in the department,",
        status: "Denied",
        author: {
            firstName: "Albert",
            lastName: "Flores",
            profilePic: avatar,
        },
        funded:"Fully Funded",
        createdAt: "2024-09-14T15:20:00",
        desc: " Fully funded four-year PhD studentship available in Stockholm to work on species diversity of Acoelomorpha including fieldwork, microscopy,eDNA and phylogenetics. We invite applications for a four-year PhD position based at the Swedish Museum of Natural History in Stockholm.PhD students at the museum are admitted to the PhD programme at the Department of Zoology, Stockholm University.The project is aimed at analysing species diversity of the marine meiofauna group Acoelomorpha in Sweden, estimate the phylogeny of select groups and describe new species. The project includes fieldwork at marine labs where specimens will be collected, identified, documented, and prepared for downstream analyses. The position is for four years. A new position as a PhD student is first for one year and then normally renewed for up to two years at a time.  The successful candidate will be supervised by Prof. Ulf Jondelius.",
        benefit: " at least 120 higher education credits in biology, and at least 30 credits from a degree project within zoological systematics, marine biology, evolutionary biology, bioinformatics, or a similar subject Experience in the study of microscopic animals, marine biological fieldwork, analysis of nucleotide sequence data, molecular lab techniques and a strong interest in biodiversity are important qualifications.",
        entryRequirements: "In order to meet the general entry requirements, the applicant must have: completed a second-cycle degree, completed courses equivalent to at least 240 higher education credits, of which 60 credits must be in the second cycle, or have otherwise acquired equivalent knowledge in Sweden or elsewhere. at least 120 higher education credits in biology, and at least 30 credits from a degree project within zoological systematics, marine biology, evolutionary biology, bioinformatics, or a similar subject. Experience in the study of microscopic animals, marine biological fieldwork, analysis of nucleotide sequence data, molecular lab techniques and a strong interest in biodiversity are important qualifications.",
        documentRequirements: "Applicants must meet both University and program requirements. Each graduate program sets their own admissions requirements. These requirements may include: a GPA higher than the university standard standardized test scores letters of recommendation statement of purpose You can upload unofficial transcripts with your application. If more academic documents are necessary, you can email them to us.SU will email you with the program's decision. If the program approves your admission, you will need to provide official transcripts. WVU needs to have your official bachelor's degree transcript before we send your University admission letter or your I-20.",
        eligibilityRegion: " Australia, Canada, Republic of Ireland, New Zealand, United Kingdom, United States and its territories, Liberia, Nigeria, Ghana, Nepal, India, Pakistan, Commonwealth Caribbean Countries (Anguilla, Antigua, The Bahamas, Barbados, Belize, British Virgin Islands, Bermuda, Cayman Islands, Dominica, Grenada, Guyana, Jamaica, Montserrat, St Kitts and Nevis, St Lucia, St Vincent, Trinidad and Tobago, Turks and Caicos).",
        howToApply: "Some programs consider applicants who do not meet those requirements for Intensive English Program (IEP) conditional admission. You may ask your program about conditional admission. Conditionally admitted students must enroll in the WVU IEP until they achieve one of the English proficiency scores listed above.",
        deadline:"15th December, 2023.",
    },
    {
        id: "003",
        tag: "Visa",
        title: "Schollarship PhD student in Software engineering",
        faetureImg: featureImg,
        content: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        status: "Pending",
        author: {
            firstName: "Albert",
            lastName: "Diddy",
            profilePic: avatar,
        },
          funded:"Fully Funded",
        createdAt: "2024-11-03T19:10:45",
        desc: " Fully funded four-year PhD studentship available in Stockholm to work on species diversity of Acoelomorpha including fieldwork, microscopy,eDNA and phylogenetics. We invite applications for a four-year PhD position based at the Swedish Museum of Natural History in Stockholm.PhD students at the museum are admitted to the PhD programme at the Department of Zoology, Stockholm University.The project is aimed at analysing species diversity of the marine meiofauna group Acoelomorpha in Sweden, estimate the phylogeny of select groups and describe new species. The project includes fieldwork at marine labs where specimens will be collected, identified, documented, and prepared for downstream analyses. The position is for four years. A new position as a PhD student is first for one year and then normally renewed for up to two years at a time.  The successful candidate will be supervised by Prof. Ulf Jondelius.",
        benefit: " at least 120 higher education credits in biology, and at least 30 credits from a degree project within zoological systematics, marine biology, evolutionary biology, bioinformatics, or a similar subject Experience in the study of microscopic animals, marine biological fieldwork, analysis of nucleotide sequence data, molecular lab techniques and a strong interest in biodiversity are important qualifications.",
        entryRequirements: "In order to meet the general entry requirements, the applicant must have: completed a second-cycle degree, completed courses equivalent to at least 240 higher education credits, of which 60 credits must be in the second cycle, or have otherwise acquired equivalent knowledge in Sweden or elsewhere. at least 120 higher education credits in biology, and at least 30 credits from a degree project within zoological systematics, marine biology, evolutionary biology, bioinformatics, or a similar subject. Experience in the study of microscopic animals, marine biological fieldwork, analysis of nucleotide sequence data, molecular lab techniques and a strong interest in biodiversity are important qualifications.",
        documentRequirements: "Applicants must meet both University and program requirements. Each graduate program sets their own admissions requirements. These requirements may include: a GPA higher than the university standard standardized test scores letters of recommendation statement of purpose You can upload unofficial transcripts with your application. If more academic documents are necessary, you can email them to us.SU will email you with the program's decision. If the program approves your admission, you will need to provide official transcripts. WVU needs to have your official bachelor's degree transcript before we send your University admission letter or your I-20.",
        eligibilityRegion: " Australia, Canada, Republic of Ireland, New Zealand, United Kingdom, United States and its territories, Liberia, Nigeria, Ghana, Nepal, India, Pakistan, Commonwealth Caribbean Countries (Anguilla, Antigua, The Bahamas, Barbados, Belize, British Virgin Islands, Bermuda, Cayman Islands, Dominica, Grenada, Guyana, Jamaica, Montserrat, St Kitts and Nevis, St Lucia, St Vincent, Trinidad and Tobago, Turks and Caicos).",
        howToApply: "Some programs consider applicants who do not meet those requirements for Intensive English Program (IEP) conditional admission. You may ask your program about conditional admission. Conditionally admitted students must enroll in the WVU IEP until they achieve one of the English proficiency scores listed above.",
        deadline:"15th December, 2023.",
    },
    
    {
        id: "004",
        tag: "Immigration",
        title: "PhD student in Zoological Systematics",
        faetureImg: featureImg,
        content: "It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        status: "Pending",
        author: {
            firstName: "Albert",
            lastName: "Flores",
            profilePic: avatar,
        },
          funded:"Fully Funded",
        createdAt: "2024-12-17T22:00:00",
        desc: " Fully funded four-year PhD studentship available in Stockholm to work on species diversity of Acoelomorpha including fieldwork, microscopy,eDNA and phylogenetics. We invite applications for a four-year PhD position based at the Swedish Museum of Natural History in Stockholm.PhD students at the museum are admitted to the PhD programme at the Department of Zoology, Stockholm University.The project is aimed at analysing species diversity of the marine meiofauna group Acoelomorpha in Sweden, estimate the phylogeny of select groups and describe new species. The project includes fieldwork at marine labs where specimens will be collected, identified, documented, and prepared for downstream analyses. The position is for four years. A new position as a PhD student is first for one year and then normally renewed for up to two years at a time.  The successful candidate will be supervised by Prof. Ulf Jondelius.",
        benefit: " at least 120 higher education credits in biology, and at least 30 credits from a degree project within zoological systematics, marine biology, evolutionary biology, bioinformatics, or a similar subject Experience in the study of microscopic animals, marine biological fieldwork, analysis of nucleotide sequence data, molecular lab techniques and a strong interest in biodiversity are important qualifications.",
        entryRequirements: "In order to meet the general entry requirements, the applicant must have: completed a second-cycle degree, completed courses equivalent to at least 240 higher education credits, of which 60 credits must be in the second cycle, or have otherwise acquired equivalent knowledge in Sweden or elsewhere. at least 120 higher education credits in biology, and at least 30 credits from a degree project within zoological systematics, marine biology, evolutionary biology, bioinformatics, or a similar subject. Experience in the study of microscopic animals, marine biological fieldwork, analysis of nucleotide sequence data, molecular lab techniques and a strong interest in biodiversity are important qualifications.",
        documentRequirements: "Applicants must meet both University and program requirements. Each graduate program sets their own admissions requirements. These requirements may include: a GPA higher than the university standard standardized test scores letters of recommendation statement of purpose You can upload unofficial transcripts with your application. If more academic documents are necessary, you can email them to us.SU will email you with the program's decision. If the program approves your admission, you will need to provide official transcripts. WVU needs to have your official bachelor's degree transcript before we send your University admission letter or your I-20.",
        eligibilityRegion: " Australia, Canada, Republic of Ireland, New Zealand, United Kingdom, United States and its territories, Liberia, Nigeria, Ghana, Nepal, India, Pakistan, Commonwealth Caribbean Countries (Anguilla, Antigua, The Bahamas, Barbados, Belize, British Virgin Islands, Bermuda, Cayman Islands, Dominica, Grenada, Guyana, Jamaica, Montserrat, St Kitts and Nevis, St Lucia, St Vincent, Trinidad and Tobago, Turks and Caicos).",
        howToApply: "Some programs consider applicants who do not meet those requirements for Intensive English Program (IEP) conditional admission. You may ask your program about conditional admission. Conditionally admitted students must enroll in the WVU IEP until they achieve one of the English proficiency scores listed above.",
        deadline:"15th December, 2023.",
    },
    {
        id: "005",
        tag: "Loans",
        title: "PhD student in Zoological Systematics",
        faetureImg: featureImg,
        content: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy.",
        status: "Denied",
        author: {
            firstName: "Albert",
            lastName: "Flores",
            profilePic: avatar,
        },
          funded:"Fully Funded",
        createdAt: "2024-04-12T11:55:20",
        desc:" Fully funded four-year PhD studentship available in Stockholm to work on species diversity of Acoelomorpha including fieldwork, microscopy,eDNA and phylogenetics. We invite applications for a four-year PhD position based at the Swedish Museum of Natural History in Stockholm.PhD students at the museum are admitted to the PhD programme at the Department of Zoology, Stockholm University.The project is aimed at analysing species diversity of the marine meiofauna group Acoelomorpha in Sweden, estimate the phylogeny of select groups and describe new species. The project includes fieldwork at marine labs where specimens will be collected, identified, documented, and prepared for downstream analyses. The position is for four years. A new position as a PhD student is first for one year and then normally renewed for up to two years at a time.  The successful candidate will be supervised by Prof. Ulf Jondelius.",
          benefit: " at least 120 higher education credits in biology, and at least 30 credits from a degree project within zoological systematics, marine biology, evolutionary biology, bioinformatics, or a similar subject Experience in the study of microscopic animals, marine biological fieldwork, analysis of nucleotide sequence data, molecular lab techniques and a strong interest in biodiversity are important qualifications.",
        entryRequirements: "In order to meet the general entry requirements, the applicant must have: completed a second-cycle degree, completed courses equivalent to at least 240 higher education credits, of which 60 credits must be in the second cycle, or have otherwise acquired equivalent knowledge in Sweden or elsewhere. at least 120 higher education credits in biology, and at least 30 credits from a degree project within zoological systematics, marine biology, evolutionary biology, bioinformatics, or a similar subject. Experience in the study of microscopic animals, marine biological fieldwork, analysis of nucleotide sequence data, molecular lab techniques and a strong interest in biodiversity are important qualifications.",
        documentRequirements: "Applicants must meet both University and program requirements. Each graduate program sets their own admissions requirements. These requirements may include: a GPA higher than the university standard standardized test scores letters of recommendation statement of purpose You can upload unofficial transcripts with your application. If more academic documents are necessary, you can email them to us.SU will email you with the program's decision. If the program approves your admission, you will need to provide official transcripts. WVU needs to have your official bachelor's degree transcript before we send your University admission letter or your I-20.",
        eligibilityRegion: " Australia, Canada, Republic of Ireland, New Zealand, United Kingdom, United States and its territories, Liberia, Nigeria, Ghana, Nepal, India, Pakistan, Commonwealth Caribbean Countries (Anguilla, Antigua, The Bahamas, Barbados, Belize, British Virgin Islands, Bermuda, Cayman Islands, Dominica, Grenada, Guyana, Jamaica, Montserrat, St Kitts and Nevis, St Lucia, St Vincent, Trinidad and Tobago, Turks and Caicos).",
        howToApply: "Some programs consider applicants who do not meet those requirements for Intensive English Program (IEP) conditional admission. You may ask your program about conditional admission. Conditionally admitted students must enroll in the WVU IEP until they achieve one of the English proficiency scores listed above.",
        deadline:"15th December, 2023.",
    },
    {
        id: "006",
        tag: "Visa",
        title: "PhD student in Zoological Systematics",
        faetureImg: featureImg,
        content: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary,",
        status: "Approved",
        author: {
            firstName: "Albert",
            lastName: "Flores",
            profilePic: avatar,
        },
          funded:"Fully Funded",
        createdAt: "2024-08-28T05:30:10",
        desc:" Fully funded four-year PhD studentship available in Stockholm to work on species diversity of Acoelomorpha including fieldwork, microscopy,eDNA and phylogenetics. We invite applications for a four-year PhD position based at the Swedish Museum of Natural History in Stockholm.PhD students at the museum are admitted to the PhD programme at the Department of Zoology, Stockholm University.The project is aimed at analysing species diversity of the marine meiofauna group Acoelomorpha in Sweden, estimate the phylogeny of select groups and describe new species. The project includes fieldwork at marine labs where specimens will be collected, identified, documented, and prepared for downstream analyses. The position is for four years. A new position as a PhD student is first for one year and then normally renewed for up to two years at a time.  The successful candidate will be supervised by Prof. Ulf Jondelius.",
          benefit: " at least 120 higher education credits in biology, and at least 30 credits from a degree project within zoological systematics, marine biology, evolutionary biology, bioinformatics, or a similar subject Experience in the study of microscopic animals, marine biological fieldwork, analysis of nucleotide sequence data, molecular lab techniques and a strong interest in biodiversity are important qualifications.",
        entryRequirements: "In order to meet the general entry requirements, the applicant must have: completed a second-cycle degree, completed courses equivalent to at least 240 higher education credits, of which 60 credits must be in the second cycle, or have otherwise acquired equivalent knowledge in Sweden or elsewhere. at least 120 higher education credits in biology, and at least 30 credits from a degree project within zoological systematics, marine biology, evolutionary biology, bioinformatics, or a similar subject. Experience in the study of microscopic animals, marine biological fieldwork, analysis of nucleotide sequence data, molecular lab techniques and a strong interest in biodiversity are important qualifications.",
        documentRequirements: "Applicants must meet both University and program requirements. Each graduate program sets their own admissions requirements. These requirements may include: a GPA higher than the university standard standardized test scores letters of recommendation statement of purpose You can upload unofficial transcripts with your application. If more academic documents are necessary, you can email them to us.SU will email you with the program's decision. If the program approves your admission, you will need to provide official transcripts. WVU needs to have your official bachelor's degree transcript before we send your University admission letter or your I-20.",
        eligibilityRegion: " Australia, Canada, Republic of Ireland, New Zealand, United Kingdom, United States and its territories, Liberia, Nigeria, Ghana, Nepal, India, Pakistan, Commonwealth Caribbean Countries (Anguilla, Antigua, The Bahamas, Barbados, Belize, British Virgin Islands, Bermuda, Cayman Islands, Dominica, Grenada, Guyana, Jamaica, Montserrat, St Kitts and Nevis, St Lucia, St Vincent, Trinidad and Tobago, Turks and Caicos).",
        howToApply: "Some programs consider applicants who do not meet those requirements for Intensive English Program (IEP) conditional admission. You may ask your program about conditional admission. Conditionally admitted students must enroll in the WVU IEP until they achieve one of the English proficiency scores listed above.",
        deadline:"15th December, 2023.",
    },
    {
        id: "007",
        tag: "Admission",
        title: "PhD student in Zoological Systematics",
        faetureImg: featureImg,
        content: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary,",
        status: "Pending",
        author: {
            firstName: "Albert",
            lastName: "Flores",
            profilePic: avatar,
        },
          funded:"Fully Funded",
        createdAt: "2024-08-28T05:30:10",
        desc:" Fully funded four-year PhD studentship available in Stockholm to work on species diversity of Acoelomorpha including fieldwork, microscopy,eDNA and phylogenetics. We invite applications for a four-year PhD position based at the Swedish Museum of Natural History in Stockholm.PhD students at the museum are admitted to the PhD programme at the Department of Zoology, Stockholm University.The project is aimed at analysing species diversity of the marine meiofauna group Acoelomorpha in Sweden, estimate the phylogeny of select groups and describe new species. The project includes fieldwork at marine labs where specimens will be collected, identified, documented, and prepared for downstream analyses. The position is for four years. A new position as a PhD student is first for one year and then normally renewed for up to two years at a time.  The successful candidate will be supervised by Prof. Ulf Jondelius.",
          benefit: " at least 120 higher education credits in biology, and at least 30 credits from a degree project within zoological systematics, marine biology, evolutionary biology, bioinformatics, or a similar subject Experience in the study of microscopic animals, marine biological fieldwork, analysis of nucleotide sequence data, molecular lab techniques and a strong interest in biodiversity are important qualifications.",
        entryRequirements: "In order to meet the general entry requirements, the applicant must have: completed a second-cycle degree, completed courses equivalent to at least 240 higher education credits, of which 60 credits must be in the second cycle, or have otherwise acquired equivalent knowledge in Sweden or elsewhere. at least 120 higher education credits in biology, and at least 30 credits from a degree project within zoological systematics, marine biology, evolutionary biology, bioinformatics, or a similar subject. Experience in the study of microscopic animals, marine biological fieldwork, analysis of nucleotide sequence data, molecular lab techniques and a strong interest in biodiversity are important qualifications.",
        documentRequirements: "Applicants must meet both University and program requirements. Each graduate program sets their own admissions requirements. These requirements may include: a GPA higher than the university standard standardized test scores letters of recommendation statement of purpose You can upload unofficial transcripts with your application. If more academic documents are necessary, you can email them to us.SU will email you with the program's decision. If the program approves your admission, you will need to provide official transcripts. WVU needs to have your official bachelor's degree transcript before we send your University admission letter or your I-20.",
        eligibilityRegion: " Australia, Canada, Republic of Ireland, New Zealand, United Kingdom, United States and its territories, Liberia, Nigeria, Ghana, Nepal, India, Pakistan, Commonwealth Caribbean Countries (Anguilla, Antigua, The Bahamas, Barbados, Belize, British Virgin Islands, Bermuda, Cayman Islands, Dominica, Grenada, Guyana, Jamaica, Montserrat, St Kitts and Nevis, St Lucia, St Vincent, Trinidad and Tobago, Turks and Caicos).",
        howToApply: "Some programs consider applicants who do not meet those requirements for Intensive English Program (IEP) conditional admission. You may ask your program about conditional admission. Conditionally admitted students must enroll in the WVU IEP until they achieve one of the English proficiency scores listed above.",
        deadline:"15th December, 2023.",
    },
    {
        id: "008",
        tag: "Scholarship",
        title: "PhD student in Zoological Systematics",
        faetureImg: featureImg,
        content: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary,",
        status: "Approved",
        author: {
            firstName: "Albert",
            lastName: "Flores",
            profilePic: avatar,
        },
          funded:"Fully Funded",
        createdAt: "2024-08-28T05:30:10",
        desc: " Fully funded four-year PhD studentship available in Stockholm to work on species diversity of Acoelomorpha including fieldwork, microscopy,eDNA and phylogenetics. We invite applications for a four-year PhD position based at the Swedish Museum of Natural History in Stockholm.PhD students at the museum are admitted to the PhD programme at the Department of Zoology, Stockholm University.The project is aimed at analysing species diversity of the marine meiofauna group Acoelomorpha in Sweden, estimate the phylogeny of select groups and describe new species. The project includes fieldwork at marine labs where specimens will be collected, identified, documented, and prepared for downstream analyses. The position is for four years. A new position as a PhD student is first for one year and then normally renewed for up to two years at a time.  The successful candidate will be supervised by Prof. Ulf Jondelius.",
        benefit: " at least 120 higher education credits in biology, and at least 30 credits from a degree project within zoological systematics, marine biology, evolutionary biology, bioinformatics, or a similar subject Experience in the study of microscopic animals, marine biological fieldwork, analysis of nucleotide sequence data, molecular lab techniques and a strong interest in biodiversity are important qualifications.",
        entryRequirements: "In order to meet the general entry requirements, the applicant must have:completed a second-cycle degree, completed courses equivalent to at least 240 higher education credits, of which 60 credits must be in the second cycle, or have otherwise acquired equivalent knowledge in Sweden or elsewhere. at least 120 higher education credits in biology, and at least 30 credits from a degree project within zoological systematics, marine biology, evolutionary biology, bioinformatics, or a similar subject. Experience in the study of microscopic animals, marine biological fieldwork, analysis of nucleotide sequence data, molecular lab techniques and a strong interest in biodiversity are important qualifications.",
        documentRequirements: "Applicants must meet both University and program requirements. Each graduate program sets their own admissions requirements. These requirements may include: a GPA higher than the university standard standardized test scores letters of recommendation statement of purpose You can upload unofficial transcripts with your application. If more academic documents are necessary, you can email them to us.SU will email you with the program's decision. If the program approves your admission, you will need to provide official transcripts. WVU needs to have your official bachelor's degree transcript before we send your University admission letter or your I-20.",
        eligibilityRegion: " Australia, Canada, Republic of Ireland, New Zealand, United Kingdom, United States and its territories, Liberia, Nigeria, Ghana, Nepal, India, Pakistan, Commonwealth Caribbean Countries (Anguilla, Antigua, The Bahamas, Barbados, Belize, British Virgin Islands, Bermuda, Cayman Islands, Dominica, Grenada, Guyana, Jamaica, Montserrat, St Kitts and Nevis, St Lucia, St Vincent, Trinidad and Tobago, Turks and Caicos).",
        howToApply: "Some programs consider applicants who do not meet those requirements for Intensive English Program (IEP) conditional admission. You may ask your program about conditional admission. Conditionally admitted students must enroll in the WVU IEP until they achieve one of the English proficiency scores listed above.",
        deadline:"15th December, 2023.",
    }
]